---
# These are supported funding model platforms

github:
- aio-libs
- jakob-keller
- thehesiod
- terrycain
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
custom:
