# Label PRs with `deps-update` label
label_prs: deps-update

schedule: every week

# https://github.com/pyupio/pyup/issues/332 ??
# Or use poetry export to create requirements.txt
requirements:
  - Poetry
