---
name: Reusable zizmor

permissions: {}

on:
  workflow_call:

env:
  FORCE_COLOR: 1

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install uv
      # yamllint disable-line rule:line-length
      uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04  # v6.0.0
      with:
        # yamllint disable-line rule:line-length
        enable-cache: | # zizmor: ignore[cache-poisoning] cache is disabled when publishing to prevent poisoning
          ${{ github.ref_type == 'tag' && 'false' || 'auto' }}
    - name: Run zizmor 🌈
      run: uvx zizmor --format=sarif . > results.sarif
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
        category: zizmor
