---
name: Reusable build

permissions: {}

on:
  workflow_call:

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false
    - name: Install uv
      # yamllint disable-line rule:line-length
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      with:
        # yamllint disable-line rule:line-length
        enable-cache: | # zizmor: ignore[cache-poisoning] cache is disabled when publishing to prevent poisoning
          ${{ github.ref_type == 'tag' && 'false' || 'auto' }}
    - name: Build distribution 📦
      run: uv build
    - name: Check distribution 📦
      run: uvx twine check --strict dist/*
    - name: Upload distribution 📦
      # yamllint disable-line rule:line-length
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
      with:
        name: python-package-distributions
        path: dist/
